### ISSUE TITLE
Semantics test for `atomic_fetch_or`

### ISSUE THREAD

**Issue by ngeorge1098** [BerkeleyLab/flang-testing-project#39]

**Comment by ktras** [comment]
The differential [D132519](https://reviews.llvm.org/D132519) and the [commit 183f1b568527bbe](https://github.com/llvm/llvm-project/commit/183f1b568527bbefb1ffa70037a71fcdbd2e15d9) closes issue #39.

**Comment by ktras** [comment]
The [Differential D133174](https://reviews.llvm.org/D133174) and the [commit aa1a2ffdbf607fb49e](https://github.com/llvm/llvm-project/commit/aa1a2ffdbf607fb49e27cab08f2f8f215ef11011) causes this test to pass.
