### ISSUE TITLE
Develop unit tests for derived type finalization

### ISSUE THREAD

**Issue by rouson** [BerkeleyLab/flang-testing-project#87]
This project involves creating one unit test corresponding to each scenario in which the Fortran 2018 that requires type finalization to occur.  A comprehensive list includes the finalizations of

- [X] A non-allocatable object on the LHS of an intrinsic assignment,
- [X] An allocated allocatable LHS of an intrinsic assignment,
- [X] A target when the associated pointer is deallocated,
- [X] An object upon explicit deallocation,
- [X] A non-pointer, non-allocatable object at the END statement,
- [X] A non-pointer non-allocatable object at the end of a block construct,
- [X] A function reference on the RHS of an intrinsic assignment,
- [X] A specification expression function result,
- [X] An intent(out) derived type dummy argument, and
- [X] An allocatable component object.

A test for each scenario now exists at https://github.com/BerkeleyLab/llvm-test-suite/tree/fortran-type-finalization/Fortran/UnitTests/finalization.

**Comment by ktras** [comment]
The type finalization tests written by @rouson were added to the [llvm-test-suite](https://github.com/llvm/llvm-test-suite) repo by Zaak Beekman. [Differential D147804](https://reviews.llvm.org/D147804) and [commit 65b897c929d7ed](https://github.com/llvm/llvm-test-suite/commit/65b897c929d7ed49c383971614aff721668d3b7c) closes issue #87.
